# Generated by Django 4.2.23 on 2025-08-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='College Name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='College Code')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='college_logos/', verbose_name='College Logo')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Contact Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
            ],
        ),
    ]
