# Generated by Django 4.2.23 on 2025-08-05 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Amount')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount Paid')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid')], default='PENDING', max_length=20, verbose_name='Status')),
                ('college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.college', verbose_name='College')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.admissionapplication', verbose_name='Student')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Installment Amount')),
                ('payment_date', models.DateField(auto_now_add=True, verbose_name='Payment Date')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='fees.studentinvoice', verbose_name='Invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Course Name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Course Code')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.college', verbose_name='College')),
            ],
        ),
    ]
