# Generated by Django 4.2.23 on 2025-08-10 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('academics', '0001_initial'),
        ('admissions', '0001_initial'),
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Course Name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Course Code')),
                ('duration_in_semesters', models.PositiveIntegerField(default=6, verbose_name='Duration in Semesters')),
                ('fee_structure_type', models.CharField(choices=[('SEMESTER_WISE', 'Semester Wise Fee'), ('YEARLY', 'Yearly Fee')], default='SEMESTER_WISE', max_length=20, verbose_name='Fee Structure Type')),
                ('subject_selection_type', models.CharField(choices=[('NONE', 'No Subjects (e.g., LLB)'), ('MAJOR_MINOR', 'Major/Minor Selection (e.g., B.A.)')], default='NONE', max_length=20, verbose_name='Subject Selection Type')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.college', verbose_name='College')),
                ('required_documents', models.ManyToManyField(blank=True, to='reception.documenttype', verbose_name='Required Documents')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text="e.g., 'Year 1 Fee' or 'Semester 1 Fee'", max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Amount')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount Paid')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=20, verbose_name='Status')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.semester', verbose_name='Semester (if applicable)')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.admissionapplication', verbose_name='Student')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Installment Amount')),
                ('payment_date', models.DateField(auto_now_add=True, verbose_name='Payment Date')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='fees.studentinvoice', verbose_name='Invoice')),
            ],
        ),
        migrations.CreateModel(
            name='YearlyFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_fees', to='fees.course')),
            ],
            options={
                'ordering': ['course', 'year'],
                'unique_together': {('course', 'year')},
            },
        ),
    ]
