# Generated by Django 4.2.23 on 2025-08-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='requires_subject_selection',
            field=models.BooleanField(default=False, verbose_name='Requires Major/Minor Subjects'),
        ),
    ]
