# Generated by Django 4.2.23 on 2025-08-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_course_requires_subject_selection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='requires_subject_selection',
        ),
        migrations.AddField(
            model_name='course',
            name='subject_selection_type',
            field=models.CharField(choices=[('NONE', 'No Subjects (e.g., LLB)'), ('MAJOR_MINOR', 'Major/Minor Selection (e.g., B.A.)'), ('TOTAL_COUNT', 'Total Subject Count Only'), ('MANUAL_ENTRY', 'Manual Subject Entry')], default='NONE', max_length=20, verbose_name='Subject Selection Type'),
        ),
    ]
