# Generated by Django 4.2.23 on 2025-08-05 18:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('VERIFIED', 'Documents Verified'), ('CONFIRMED', 'Admission Confirmed'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=20, verbose_name='Application Status')),
                ('roll_number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Roll Number / Unique ID')),
                ('samarth_registration_no', models.CharField(max_length=50, unique=True, verbose_name='Samarth Portal Registration No.')),
                ('full_name', models.CharField(max_length=100, verbose_name='Student Name')),
                ('father_name', models.CharField(max_length=100, verbose_name="Father's Name")),
                ('mother_name', models.CharField(max_length=100, verbose_name="Mother's Name")),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('mobile_number', models.CharField(max_length=15, verbose_name='Mobile Number')),
                ('category', models.CharField(choices=[('GENERAL', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('EWS', 'EWS'), ('MANAGEMENT', 'Management Quota'), ('SPORTS', 'Sports Quota')], default='GENERAL', max_length=20, verbose_name='Category')),
                ('course_enrolled', models.CharField(max_length=100, verbose_name='Course Enrolled')),
                ('samarth_password', encrypted_model_fields.fields.EncryptedCharField(verbose_name='Samarth Portal Password (Encrypted)')),
                ('application_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.college', verbose_name='College')),
                ('major_subjects', models.ManyToManyField(blank=True, limit_choices_to={'subject_type': 'MAJOR'}, related_name='major_applications', to='academics.subject', verbose_name='Major Subjects')),
                ('minor_subjects', models.ManyToManyField(blank=True, limit_choices_to={'subject_type': 'MINOR'}, related_name='minor_applications', to='academics.subject', verbose_name='Minor Subjects')),
            ],
        ),
    ]
