# Generated by Django 4.2.23 on 2025-08-10 14:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('CONFIRMED', 'Admission Confirmed')], default='SUBMITTED', max_length=20)),
                ('roll_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15, null=True)),
                ('samarth_registration_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('category', models.CharField(choices=[('GENERAL', 'General'), ('OBC', 'OBC')], default='GENERAL', max_length=20)),
                ('total_subjects_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total Subjects Count')),
                ('manually_entered_subjects', models.TextField(blank=True, verbose_name='Manually Entered Subjects')),
                ('samarth_password', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('application_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.college')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='student_documents/')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admissions.admissionapplication')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reception.documenttype')),
            ],
        ),
    ]
