# Generated by Django 4.2.23 on 2025-08-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='manually_entered_subjects',
            field=models.TextField(blank=True, verbose_name='Manually Entered Subjects'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='total_subjects_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Total Subjects Count'),
        ),
    ]
