# Generated by Django 4.2.23 on 2025-08-10 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fees', '0001_initial'),
        ('academics', '0002_initial'),
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fees.course'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='current_semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.semester'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='major_subjects',
            field=models.ManyToManyField(blank=True, related_name='major_applications', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='minor_subjects',
            field=models.ManyToManyField(blank=True, related_name='minor_applications', to='academics.subject'),
        ),
    ]
