# Generated by Django 4.2.23 on 2025-08-10 14:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Document Name')),
                ('is_required', models.BooleanField(default=True, verbose_name='Is this document mandatory?')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True, help_text='Only active notices will be shown on the website.')),
                ('college', models.ForeignKey(blank=True, help_text='Select a college to make this notice college-specific. Leave blank for a general notice.', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.college')),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
    ]
