# Generated by Django 4.2.23 on 2025-08-05 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0001_initial'),
        ('core', '0001_initial'),
        ('admissions', '0001_initial'),
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.course', verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.college', verbose_name='College'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Account'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.faculty', verbose_name='Faculty'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject', verbose_name='Subject'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='scheduled_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.classschedule', verbose_name='Class'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.admissionapplication', verbose_name='Student'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'scheduled_class', 'date')},
        ),
    ]
