# Generated by Django 4.2.23 on 2025-08-10 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fees', '0001_initial'),
        ('core', '0001_initial'),
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='fees.course'),
        ),
        migrations.AddField(
            model_name='semester',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='fees.course'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.college'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.faculty'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.semester'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='scheduled_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.classschedule'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.admissionapplication'),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('course', 'semester_number')},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'scheduled_class', 'date')},
        ),
    ]
