# Generated by Django 4.2.23 on 2025-08-05 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('admissions', '0001_initial'),
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Unit Test Name')),
                ('date', models.DateField(verbose_name='Test Date')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.college', verbose_name='College')),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.FloatField(verbose_name='Marks Obtained')),
                ('max_marks', models.FloatField(default=100, verbose_name='Maximum Marks')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.admissionapplication', verbose_name='Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject', verbose_name='Subject')),
                ('unit_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examinations.unittest', verbose_name='Unit Test')),
            ],
            options={
                'unique_together': {('student', 'unit_test', 'subject')},
            },
        ),
    ]
